In [86]:
import pandas as pd 
import numpy  as np
import os 
import time

In [87]:
def roin(data,object_):
    pinpai_ID = data.drop_duplicates(subset=object_,inplace=False)
    pinpai_list_ID = list(pinpai_ID[object_])
    pinpai_dict_list = []
    
    
    for nameid in pinpai_list_ID:
        for_dict = {}

        df_for_x = data[data[object_] == nameid ]
        
        dingdan_std =  df_for_x['订单数'].std()
    #     订单总数
        dingdan_sum =  df_for_x['订单数'].sum()
        
        dingdan_baoguangrenshu  =  df_for_x['曝光人数'].sum()
    #     金额总数
        jin_sum =  df_for_x['实付交易额'].sum()
    #     平均订单数
        dingdan_mean = dingdan_sum/df_for_x['门店ID'].count()
    #     平均金额
        jin_mean = jin_sum/df_for_x['门店ID'].count()
    #     均客单价
        kedanjia_mean = df_for_x['客单价'].mean()
    #     最小客单价
        kedanjia_min = df_for_x['客单价'].min()
    #     最大客单价
        kedanjia_max = df_for_x['客单价'].max()
    #     非议订单
        feiyi =  df_for_x['非异订单数'].sum()
    #     拒单
        judan  =  df_for_x['商家拒单订单数'].sum()
    #     bujied不接单
        bujiedan =  df_for_x['商家不接单订单数'].sum()
    #     投诉D单
        tousu =  df_for_x['商家违规投诉订单数'].sum()
        
        time =  df_for_x['时间'].mean()

        pinpai_dict_list__count = df_for_x.drop_duplicates(subset = '蜂窝')['蜂窝'].count()
        for_dict[object_] = nameid
        for_dict['门店总数'] = df_for_x['门店ID'].count()
        for_dict['订单数'] = dingdan_sum
        for_dict['曝光人数'] = dingdan_baoguangrenshu
        for_dict['订单方差'] = dingdan_std
        for_dict['实付交易额'] = jin_sum
        for_dict['平均订单数'] = dingdan_mean
        for_dict['平均金额'] = jin_mean
        for_dict['均客单价'] = kedanjia_mean
        for_dict['最小客单价'] = kedanjia_min
        for_dict['最大客单价'] = kedanjia_max
        for_dict['非议订单数'] = feiyi
        for_dict['拒单'] = judan
        for_dict['不接订单'] = bujiedan
        for_dict['time'] = time
        for_dict['蜂窝数量']  = pinpai_dict_list__count
        pinpai_dict_list.append(for_dict) 
    for i in range(len(pinpai_dict_list)):

        dataframe_i = pd.DataFrame([pinpai_dict_list[i]])
        dataframe_i = dataframe_i.fillna(0)
        if i == 0:
            pinpai_dict_dataframe1 = dataframe_i
        else:
            pinpai_dict_dataframe1 = pd.concat([pinpai_dict_dataframe1,dataframe_i],axis=0)
    
    pinpai_dict_dataframe1 = pinpai_dict_dataframe1.sort_values(by='订单数',ascending=False)
    
    return pinpai_dict_dataframe1

In [88]:
route = r"C:/Users/Administrator/Datas/1训练模型/美团全国/"

In [89]:
null_data = pd.DataFrame()
for i in range(1,9):
    url = route + str(i) + '月/大连整月数据.csv'
    data = pd.read_csv(url,encoding='utf8')
    data['时间'] = i
    null_data= pd.concat([null_data,data],axis=0)

In [90]:
df = null_data
df_pinpai = df[df['品牌ID'] > 0]

In [94]:
enght = df_pinpai[df_pinpai['时间'] == 8 ]

In [95]:
enght = roin(enght,'蜂窝')

<ipython-input-87-df31c56da28f>:20: RuntimeWarning: invalid value encountered in longlong_scalars
  dingdan_mean = dingdan_sum/df_for_x['门店ID'].count()
<ipython-input-87-df31c56da28f>:22: RuntimeWarning: invalid value encountered in double_scalars
  jin_mean = jin_sum/df_for_x['门店ID'].count()

In [96]:
df_pinpai = roin(df_pinpai,'蜂窝')

<ipython-input-87-df31c56da28f>:20: RuntimeWarning: invalid value encountered in longlong_scalars
  dingdan_mean = dingdan_sum/df_for_x['门店ID'].count()
<ipython-input-87-df31c56da28f>:22: RuntimeWarning: invalid value encountered in double_scalars
  jin_mean = jin_sum/df_for_x['门店ID'].count()

In [97]:
df_pinpai.sort_values(by = '曝光人数',ascending = False)

,蜂窝,门店总数,订单数,曝光人数,订单方差,实付交易额,平均订单数,平均金额,均客单价,最小客单价,最大客单价,非议订单数,拒单,不接订单,time,蜂窝数量
0,旅顺新开,59,607,405980.0,11.851162,60087.940032,10.288136,1018.439662,108.052787,29.689362,179.085715,19,2,2,4.627119,1
0,辽宁师范大学,33,1317,297154.0,81.675564,74065.350113,39.909091,2244.404549,92.108673,12.851282,188.000000,15,5,0,4.969697,1
0,万和汇,37,1404,282541.0,69.369760,158506.490005,37.945946,4283.959189,114.914686,43.750000,204.880000,71,9,0,4.783784,1
0,甘井子万达广场,24,608,221235.0,36.922559,62502.060059,25.333333,2604.252502,101.264617,48.000000,180.000000,20,2,1,4.500000,1
0,金州体育场,31,176,168970.0,9.199229,20868.910004,5.677419,673.190645,112.665672,7.000000,190.000000,8,1,1,4.967742,1
0,时代广场,32,1197,158931.0,59.384401,139723.080015,37.406250,4366.346250,110.150813,10.000000,208.716670,10,1,0,4.500000,1
0,奥林匹克,49,225,144196.0,8.149433,19713.840015,4.591837,402.323266,130.909544,14.995263,346.000000,10,8,0,4.979592,1
0,红梅,25,137,135776.0,5.767148,12991.800005,5.480000,519.672000,99.306277,37.799999,255.000000,17,8,3,5.040000,1
0,友好广场,32,154,132056.0,6.930240,16809.620009,4.812500,525.300625,107.153079,54.100000,146.000000,17,4,2,4.812500,1
0,金州古城,26,169,128993.0,4.310452,18858.389984,6.500000,725.322692,111.402892,75.000000,191.000000,3,1,0,4.730769,1
0,泉水东,16,56,123306.0,3.119829,6655.580002,3.500000,415.973750,114.286277,52.200001,172.000000,3,2,0,4.500000,1
0,金州安盛,32,81,112704.0,3.005204,6578.540012,2.531250,205.579375,85.384229,14.300000,175.500000,8,1,4,4.875000,1
0,太原街,34,339,108460.0,15.664059,27322.100092,9.970588,803.591179,92.965629,15.000000,206.899994,14,8,0,4.911765,1
0,八一路西,16,313,106392.0,30.594049,17891.500021,19.562500,1118.218751,104.966285,20.382857,181.142857,9,4,0,4.500000,1
0,红星海,24,40,101673.0,2.958652,3189.299988,1.666667,132.887499,85.856778,18.500000,157.000000,2,0,1,4.500000,1
0,春柳西,23,38,101421.0,2.102135,3554.700001,1.652174,154.552174,118.621633,26.842857,194.500000,4,1,1,4.347826,1
0,万达广场,24,112,99995.0,6.055301,11148.300009,4.666667,464.512500,108.284571,58.614286,187.000000,2,2,0,4.500000,1
0,泡崖子,24,60,86194.0,3.375101,7394.000002,2.500000,308.083333,124.014039,62.000000,213.000000,2,0,1,4.500000,1
0,华南广场,11,50,73099.0,3.856518,7240.149985,4.545455,658.195453,164.236607,41.785714,326.666667,2,0,0,3.818182,1
0,锦辉广场,16,75,69065.0,4.556589,6890.740009,4.687500,430.671251,104.570651,10.000000,297.500000,1,0,0,5.500000,1
0,泉水西,12,179,62159.0,15.060233,21816.600014,14.916667,1818.050001,156.426769,69.093334,453.000000,10,10,0,3.833333,1
0,中长街,19,96,61561.0,10.895839,7581.700006,5.052632,399.036842,90.639854,9.333333,181.000000,4,2,0,5.368421,1
0,和平广场,23,30,61077.0,1.690476,5377.300041,1.304348,233.795654,220.714585,56.500000,996.000000,1,1,0,3.782609,1
0,天津街,15,105,59534.0,16.514063,1816.900015,7.000000,121.126668,37.635606,8.839344,71.800003,4,1,2,5.400000,1
0,大连财经学院,8,51,57853.0,2.973094,5628.000000,6.375000,703.500000,115.909226,78.700000,259.166667,0,0,0,4.500000,1
0,金三角,11,34,56834.0,2.736953,4217.500000,3.090909,383.409091,159.569444,62.666667,419.000000,2,2,0,3.818182,1
0,五一广场,25,26,56633.0,2.091252,2107.299997,1.040000,84.292000,118.259896,29.266666,292.000000,0,0,0,5.040000,1
0,大连科技学院,8,200,55265.0,10.875924,24492.400013,25.000000,3061.550002,122.567905,109.019231,140.507692,0,0,0,4.500000,1
0,小平岛,18,20,54917.0,1.367217,3313.400002,1.111111,184.077778,164.530833,99.000000,210.000000,1,0,0,4.166667,1
0,二七广场,24,15,50682.0,1.095941,1610.000000,0.625000,67.083333,104.333333,66.000000,188.000000,5,1,2,4.500000,1
0,锦绣,11,64,49161.0,9.389549,4552.300053,5.818182,413.845459,82.262620,67.706668,118.850000,0,0,0,6.272727,1
0,五彩城,21,11,45651.0,0.813575,1482.900002,0.523810,70.614286,144.279167,80.000000,222.000000,5,2,1,4.142857,1
0,南关岭,16,32,45586.0,1.966384,3377.589989,2.000000,211.099374,105.980500,66.950001,155.449997,2,1,1,4.500000,1
0,亿合城,9,49,41446.0,6.002314,3317.200001,5.444444,368.577778,60.714469,12.537500,99.894737,6,1,0,6.888889,1
0,八一路东,12,28,39953.0,1.969464,2902.179993,2.333333,241.848333,102.559642,7.000000,265.000000,2,0,0,5.166667,1
0,春柳东,22,25,39038.0,1.983154,2466.000000,1.136364,112.090909,127.108333,37.200000,263.000000,2,2,0,5.454545,1
0,高新万达,8,50,34131.0,4.652188,6779.460011,6.250000,847.432501,151.736128,91.192000,329.000000,10,2,1,4.500000,1
0,东方圣克拉,14,11,33864.0,1.188313,1311.599998,0.785714,93.685714,136.258333,44.500000,265.000000,1,1,0,6.714286,1
0,旅顺新玛特,17,38,33706.0,3.419236,2975.710001,2.235294,175.041765,86.499237,18.000000,155.000000,1,0,0,5.647059,1
0,东北财经大学,8,2,33444.0,0.462910,229.000000,0.250000,28.625000,114.500000,35.000000,194.000000,0,0,0,4.500000,1
0,千山路,9,7,32801.0,1.986063,889.000000,0.777778,98.777778,142.833333,120.666667,165.000000,4,0,0,4.444444,1
0,凯旋,23,18,32668.0,1.881888,1373.100006,0.782609,59.700000,92.385318,47.000000,203.050003,1,1,0,4.347826,1
0,青泥洼,9,3,27268.0,0.707107,185.000000,0.333333,20.555556,55.000000,35.000000,75.000000,1,0,0,4.555556,1
0,罗斯福,8,4,23641.0,0.755929,642.000000,0.500000,80.250000,177.166667,110.500000,285.000000,0,0,0,2.500000,1
0,沙河口,12,17,21148.0,3.117643,1545.500000,1.416667,128.791667,102.627273,65.000000,152.500000,1,0,0,5.166667,1
0,张前路乐购,8,7,18808.0,1.457738,1220.000000,0.875000,152.500000,173.250000,105.000000,272.000000,2,0,1,4.500000,1
0,大连海事大学,11,2,14479.0,0.404520,165.900000,0.181818,15.081818,82.950000,16.900000,149.000000,2,1,0,5.181818,1
0,软件园,11,2,13086.0,0.603023,209.800003,0.181818,19.072728,104.900002,104.900002,104.900002,0,0,0,4.636364,1
0,大连理工大学,8,6,11555.0,0.707107,739.000000,0.750000,92.375000,129.500000,85.000000,225.000000,2,1,0,4.500000,1
0,辽宁师范大学海华学院,2,15,9760.0,4.949747,1039.799995,7.500000,519.899998,56.140909,27.900000,84.381818,2,1,0,7.500000,1
0,东城天下,9,4,7075.0,0.726483,593.000000,0.444444,65.888889,133.833333,105.000000,191.500000,0,0,0,4.777778,1
0,南山,3,2,5196.0,1.154701,94.000000,0.666667,31.333333,47.000000,47.000000,47.000000,0,0,0,2.000000,1
0,凯丹广场,1,0,619.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,7.000000,1
0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0.000000,0

In [103]:
df_pinpai[df_pinpai['订单数'] > 200]

,蜂窝,门店总数,订单数,曝光人数,订单方差,实付交易额,平均订单数,平均金额,均客单价,最小客单价,最大客单价,非议订单数,拒单,不接订单,time,蜂窝数量
0,万和汇,37,1404,282541.0,69.369760,158506.490005,37.945946,4283.959189,114.914686,43.750000,204.880000,71,9,0,4.783784,1
0,辽宁师范大学,33,1317,297154.0,81.675564,74065.350113,39.909091,2244.404549,92.108673,12.851282,188.000000,15,5,0,4.969697,1
0,时代广场,32,1197,158931.0,59.384401,139723.080015,37.406250,4366.346250,110.150813,10.000000,208.716670,10,1,0,4.500000,1
0,甘井子万达广场,24,608,221235.0,36.922559,62502.060059,25.333333,2604.252502,101.264617,48.000000,180.000000,20,2,1,4.500000,1
0,旅顺新开,59,607,405980.0,11.851162,60087.940032,10.288136,1018.439662,108.052787,29.689362,179.085715,19,2,2,4.627119,1
0,太原街,34,339,108460.0,15.664059,27322.100092,9.970588,803.591179,92.965629,15.000000,206.899994,14,8,0,4.911765,1
0,八一路西,16,313,106392.0,30.594049,17891.500021,19.562500,1118.218751,104.966285,20.382857,181.142857,9,4,0,4.500000,1
0,奥林匹克,49,225,144196.0,8.149433,19713.840015,4.591837,402.323266,130.909544,14.995263,346.000000,10,8,0,4.979592,1

In [100]:
enght['门店总数'].mean()

2.803921568627451

In [102]:
df_pinpai.to_csv('1.csv')