In [6]:
import pandas as pd 
import numpy  as np
import os 
import time

In [7]:
route = r"C:/Users/Administrator/Datas/4门店模型/张家口门店/张家口.csv"
# null_data = pd.DataFrame()
# for i in range(1,9):
#     url = route + str(i) + '月/大连整月数据.csv'
#     data = pd.read_csv(url,encoding='utf8')
#     data['时间'] = i
#     null_data= pd.concat([null_data,data],axis=0)
# df = null_data

In [8]:
df = pd.read_csv(route,encoding='utf8')

In [9]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,poi_id,门店名,品牌ID,品牌名,省份,城市,城市等级,...,商家经营状态异常订单数,商家违规投诉订单数,美团配送延迟订单数,因美团配送原因取消订单数,线上活动总补贴金额,曝光人数,进店人数,成单用户数,在线商品数,在售商品数
0,343,343,343,9361775,欢欢的花店（华佳广场店）,11035,鼎卉鲜花,河北省,张家口,D1,...,0,0,0,0,346.00,303,30,2,760,752
1,449,449,449,5337828,如愿鲜花（丽鑫鲜花店）,100012196,如愿鲜花,河北省,张家口,D1,...,0,0,0,0,190.42,295,20,1,772,769
2,740,740,740,8321049,浪漫花都(柴沟堡花店),0,NaN,河北省,张家口,D1,...,0,0,0,0,0.00,13,3,0,312,292
3,1010,1010,1010,9384070,沁香阁花卉旗舰店,0,NaN,河北省,张家口,D1,...,0,0,0,0,0.00,22,0,0,17,17
4,1300,1300,1300,9670957,花花世界（宣府大街支家桥店）,11035,鼎卉鲜花,河北省,张家口,D1,...,0,0,0,0,675.00,479,32,7,757,751
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5060,2271792,89283,89283,9028638,巧巧花坊（张家口店）,0,NaN,河北省,张家口,D1,...,0,0,0,0,0.00,107,1,0,249,249
5061,2271925,89416,89416,9131026,海林超市鲜花店,0,NaN,河北省,张家口,D1,...,0,0,0,0,0.00,84,2,0,64,63
5062,2273075,90566,90566,4950879,鲜花到（怡花都鲜花礼品）,100028370,鲜花网,河北省,张家口,D1,...,0,0,0,0,0.00,98,9,0,468,324
5063,2273636,91127,91127,9231667,奇欣花卉（鲜花，绿植，生日花表白）,100003909,一家花店,河北省,张家口,D1,...,0,0,0,0,0.00,62,2,0,487,444
5064,2274342,91833,91833,6513955,如愿鲜花（花恋鲜花坊）,100012196,如愿鲜花,河北省,张家口,D1,...,0,0,0,0,103.00,305,3,1,770,769

In [17]:
data = df[df['品牌ID'] == 0]

In [18]:
data

,Unnamed: 0,门店ID,门店名称,品牌ID,品牌名称,省份,城市,城市等级,蜂窝,首次上线时间,...,因美团配送原因取消订单数,曝光人数,进店人数,下单人数,动销商品数,gtv订单数,原价gtv,实付gtv,客单价,时间
0,0,339869,娜娜鲜花,0,NaN,辽宁省,大连,B1,华南广场,20150812.0,...,0,9145.0,89.0,1.0,1.0,1,228.000000,228.000000,228.000000,1
2,0,368572,旅顺迎春鲜花店,0,NaN,辽宁省,大连,B1,旅顺新开,20150815.0,...,0,9978.0,118.0,0.0,0.0,1,59.000000,59.000000,NaN,1
3,0,378672,致美花艺,0,NaN,辽宁省,大连,B1,万达广场,20150824.0,...,0,11651.0,206.0,7.0,11.0,9,1380.799988,1373.799988,166.542855,1
4,0,402025,巧手鲜花店,0,NaN,辽宁省,大连,B1,和平广场,20150901.0,...,0,1625.0,11.0,0.0,0.0,0,0.000000,0.000000,NaN,1
6,0,580086,如意鲜花店,0,NaN,辽宁省,大连,B1,金州古城,20151202.0,...,0,1755.0,61.0,1.0,1.0,1,39.000000,34.000000,34.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,0,9805107,温馨鲜花,0,NaN,辽宁省,大连,B1,NaN,20200823.0,...,0,318.0,12.0,0.0,0.0,0,0.000000,0.000000,NaN,8
682,0,9807727,千姿鲜花店,0,NaN,辽宁省,大连,B1,NaN,20200824.0,...,0,128.0,0.0,0.0,0.0,0,0.000000,0.000000,NaN,8
683,0,9818711,清源鲜花(广场店),0,NaN,辽宁省,大连,B1,凯旋,20200824.0,...,0,1008.0,20.0,0.0,0.0,0,0.000000,0.000000,NaN,8
684,0,9819376,秀觉花影,0,NaN,辽宁省,大连,B1,辽宁师范大学,20200825.0,...,0,75.0,2.0,0.0,0.0,0,0.000000,0.000000,NaN,8
685,0,9822091,路上有花鲜花店,0,NaN,辽宁省,大连,B1,青泥洼,20200824.0,...,0,2003.0,46.0,0.0,0.0,0,0.000000,0.000000,NaN,8

In [19]:
def roin(data,object_):
    pinpai_ID = data.drop_duplicates(subset=object_,inplace=False)
    pinpai_list_ID = list(pinpai_ID[object_])
    pinpai_dict_list = []
    
    
    for nameid in pinpai_list_ID:
        for_dict = {}

        df_for_x = data[data[object_] == nameid ]
        
        dingdan_std =  df_for_x['订单数'].std()
    #     订单总数
        dingdan_sum =  df_for_x['订单数'].sum()
        
        dingdan_baoguangrenshu  =  df_for_x['曝光人数'].sum()
    #     金额总数
        jin_sum =  df_for_x['实付交易额'].sum()
    #     平均订单数
        dingdan_mean = dingdan_sum/df_for_x['门店ID'].count()
    #     平均金额
        jin_mean = jin_sum/df_for_x['门店ID'].count()
    #     均客单价
        kedanjia_mean = df_for_x['客单价'].mean()
    #     最小客单价
        kedanjia_min = df_for_x['客单价'].min()
    #     最大客单价
        kedanjia_max = df_for_x['客单价'].max()
    #     非议订单
        feiyi =  df_for_x['非异订单数'].sum()
    #     拒单
        judan  =  df_for_x['商家拒单订单数'].sum()
    #     bujied不接单
        bujiedan =  df_for_x['商家不接单订单数'].sum()
    #     投诉D单
        tousu =  df_for_x['商家违规投诉订单数'].sum()
        
        time =  df_for_x['时间'].mean()

        pinpai_dict_list__count = df_for_x.drop_duplicates(subset = '蜂窝')['蜂窝'].count()
        for_dict[object_] = nameid
        for_dict['门店总数'] = df_for_x['门店ID'].count()
        for_dict['订单数'] = dingdan_sum
        for_dict['曝光人数'] = dingdan_baoguangrenshu
        for_dict['订单方差'] = dingdan_std
        for_dict['实付交易额'] = jin_sum
        for_dict['平均订单数'] = dingdan_mean
        for_dict['平均金额'] = jin_mean
        for_dict['均客单价'] = kedanjia_mean
        for_dict['最小客单价'] = kedanjia_min
        for_dict['最大客单价'] = kedanjia_max
        for_dict['非议订单数'] = feiyi
        for_dict['拒单'] = judan
        for_dict['不接订单'] = bujiedan
        for_dict['time'] = time
        for_dict['蜂窝数量']  = pinpai_dict_list__count
        pinpai_dict_list.append(for_dict) 
    for i in range(len(pinpai_dict_list)):

        dataframe_i = pd.DataFrame([pinpai_dict_list[i]])
        dataframe_i = dataframe_i.fillna(0)
        if i == 0:
            pinpai_dict_dataframe1 = dataframe_i
        else:
            pinpai_dict_dataframe1 = pd.concat([pinpai_dict_dataframe1,dataframe_i],axis=0)
    
    pinpai_dict_dataframe1 = pinpai_dict_dataframe1.sort_values(by='订单数',ascending=False)
    
    return pinpai_dict_dataframe1

In [24]:
data_fengwo= roin(data,'蜂窝')
df_fengwo= roin(df,'蜂窝')

<ipython-input-19-df31c56da28f>:20: RuntimeWarning: invalid value encountered in longlong_scalars
  dingdan_mean = dingdan_sum/df_for_x['门店ID'].count()
<ipython-input-19-df31c56da28f>:22: RuntimeWarning: invalid value encountered in double_scalars
  jin_mean = jin_sum/df_for_x['门店ID'].count()

In [25]:
data_fengwo

,蜂窝,门店总数,订单数,曝光人数,订单方差,实付交易额,平均订单数,平均金额,均客单价,最小客单价,最大客单价,非议订单数,拒单,不接订单,time,蜂窝数量
0,软件园,32,6824,318436.0,401.580667,703303.080289,213.250000,21978.221259,96.146195,24.000000,142.000000,90,3,1,4.500000,1
0,辽宁师范大学海华学院,34,4070,345009.0,231.670943,275010.299884,119.705882,8088.538232,81.417370,20.956522,129.844828,24,2,1,4.705882,1
0,锦辉广场,70,3120,307670.0,139.563873,181956.590018,44.571429,2599.379857,96.741807,16.000000,225.880005,69,3,1,5.171429,1
0,大连交通大学,43,2250,275120.0,112.761383,223476.609816,52.325581,5197.130461,100.635843,28.768421,193.000000,53,12,4,4.674419,1
0,万和汇,111,1924,546783.0,38.127855,213022.830085,17.333333,1919.124595,103.452042,4.500000,289.000000,117,10,1,4.972973,1
0,凯旋,68,1676,313649.0,50.711288,216387.989994,24.647059,3182.176323,120.964947,1.000000,234.125000,64,18,2,4.485294,1
0,东方圣克拉,81,1256,375296.0,32.464644,136012.890091,15.506173,1679.171483,126.860963,69.484153,266.572964,59,6,0,5.160494,1
0,金三角,50,1249,436266.0,48.964164,171929.430119,24.980000,3438.588602,140.100326,44.100000,349.227273,89,6,3,5.260000,1
0,沙河口,103,1106,287280.0,24.392606,95310.780063,10.737864,925.347379,99.894181,2.677143,287.187500,57,6,3,5.000000,1
0,万达广场,115,1075,578045.0,13.190935,108892.640037,9.347826,946.892522,113.864254,18.860000,338.000000,34,6,5,4.660870,1
0,奥林匹克,144,910,573142.0,18.953256,116208.860048,6.319444,807.005973,155.286822,17.500000,412.000000,44,14,4,4.652778,1
0,金州古城,115,810,389152.0,14.717451,87696.550013,7.043478,762.578696,111.448397,3.981818,237.000000,47,2,1,4.600000,1
0,时代广场,22,750,61876.0,99.168404,85377.499992,34.090909,3880.795454,98.834163,39.842105,127.000000,84,3,0,5.681818,1
0,罗斯福,15,676,94422.0,103.778932,23947.499997,45.066667,1596.500000,78.234549,13.981333,255.000000,2,0,0,2.600000,1
0,南山,77,653,249839.0,14.443730,92688.649959,8.480519,1203.748701,120.287342,2.100000,224.000000,41,10,10,4.753247,1
0,中长街,41,575,109484.0,36.041981,24000.759955,14.024390,585.384389,85.129919,21.989423,250.000000,8,1,0,4.658537,1
0,金州安盛,77,523,235087.0,23.951342,61493.920019,6.792208,798.622338,118.220995,11.250000,217.000000,36,10,1,4.649351,1
0,金州体育场,63,473,225835.0,16.000880,68165.379806,7.507937,1081.990156,123.732805,17.176190,246.961626,29,3,0,4.587302,1
0,东北财经大学,13,440,67605.0,19.234718,46188.130005,33.846154,3552.933077,110.732416,78.497465,153.855554,26,3,6,5.076923,1
0,旅顺新开,58,423,311848.0,20.036816,57367.519977,7.293103,989.095172,150.591060,5.000000,480.000000,13,2,2,5.155172,1
0,春柳东,74,415,278674.0,20.091447,31774.099913,5.608108,429.379729,124.131730,21.698101,208.000000,23,7,1,4.648649,1
0,张前路乐购,35,320,161419.0,26.451001,40072.540009,9.142857,1144.929715,187.057972,2.000000,862.500000,23,1,0,5.114286,1
0,高新万达,61,314,172953.0,11.367844,24501.999931,5.147541,401.672130,115.109851,18.537500,881.200012,26,8,3,4.770492,1
0,青泥洼,49,271,80466.0,17.012375,17245.380066,5.530612,351.946532,93.536513,42.296809,188.500000,12,4,2,5.265306,1
0,五一广场,46,265,165428.0,10.411926,34423.219995,5.760870,748.330869,124.121067,70.625000,242.090909,15,1,2,4.739130,1
0,红梅,62,236,144915.0,8.875900,28538.260086,3.806452,460.294518,141.994963,72.000000,436.000000,11,4,0,4.629032,1
0,太原街,25,230,96803.0,25.818275,6607.099921,9.200000,264.283997,166.897194,17.076744,595.000000,2,0,0,4.360000,1
0,亿合城,25,223,97396.0,15.269578,27627.449989,8.920000,1105.098000,124.872407,26.496875,266.500000,9,1,0,6.680000,1
0,南关岭,39,215,237682.0,7.660122,28542.090057,5.512821,731.848463,126.444241,62.000000,252.690001,12,1,2,5.641026,1
0,友好广场,28,210,100028.0,17.336538,25056.759968,7.500000,894.884285,170.338841,25.000000,804.500000,26,3,0,4.214286,1
0,辽宁师范大学,52,208,81843.0,15.770412,7545.100001,4.000000,145.098077,80.667392,9.000000,222.333333,1,1,0,5.057692,1
0,华南广场,40,192,161373.0,13.582039,24411.520000,4.800000,610.288000,145.387180,22.799999,313.500000,16,1,3,4.875000,1
0,千山路,73,179,150126.0,9.823499,30237.000000,2.452055,414.205479,161.922815,65.000000,358.000000,16,4,3,4.698630,1
0,和平广场,63,171,226696.0,6.230592,18020.160004,2.714286,286.034286,133.009802,17.199999,391.839996,14,5,0,4.174603,1
0,二七广场,88,143,162983.0,4.191706,17207.499990,1.625000,195.539773,136.962790,22.500000,389.000000,8,3,0,4.363636,1
0,五彩城,24,134,103911.0,9.347944,12550.400000,5.583333,522.933333,95.463045,20.000000,242.000000,5,1,3,5.041667,1
0,泉水西,69,108,153837.0,4.815655,17086.400032,1.565217,247.628986,148.672054,79.000000,220.600002,16,3,4,4.333333,1
0,锦绣,45,90,125897.0,5.547317,8911.799995,2.000000,198.040000,125.138466,52.083333,261.000000,8,2,1,5.200000,1
0,甘井子万达广场,29,81,113556.0,5.253430,6744.700001,2.793103,232.575862,102.900992,7.775000,243.166667,4,0,0,5.344828,1
0,东城天下,52,72,121782.0,2.958231,13002.020004,1.384615,250.038846,205.229239,95.333333,354.000000,2,0,1,5.019231,1
0,天津街,25,55,37258.0,6.103278,3950.400000,2.200000,158.016000,97.252421,40.882353,183.000000,1,1,0,4.640000,1
0,春柳西,77,51,49483.0,3.526629,5602.359994,0.662338,72.757922,109.472667,0.230000,188.000000,5,4,1,4.805195,1
0,旅顺新玛特,64,43,127663.0,1.285508,3800.319996,0.671875,59.380000,107.086458,10.666667,319.049988,1,0,0,4.625000,1
0,泡崖子,30,41,72899.0,2.894505,4908.300020,1.366667,163.610001,107.109694,49.900002,231.050001,6,2,1,4.733333,1
0,八一路西,34,39,55071.0,2.524214,2808.700008,1.147059,82.608824,93.280247,10.000000,186.000000,0,0,0,5.058824,1
0,红星海,30,37,30975.0,3.147887,3951.599997,1.233333,131.720000,181.927936,30.000000,535.000000,0,0,0,4.833333,1
0,大连民族大学,16,34,26985.0,2.680174,4839.760014,2.125000,302.485001,174.713228,114.590002,469.989990,2,1,0,3.750000,1
0,小平岛,49,34,61410.0,2.043323,2376.900000,0.693878,48.508163,87.119365,10.900000,167.500000,4,2,1,4.918367,1
0,马栏广场,42,30,127125.0,1.469789,2194.800008,0.714286,52.257143,93.041026,7.150000,219.900002,2,0,1,4.976190,1
0,泉水东,23,19,109524.0,1.922408,3051.860016,0.826087,132.689566,182.463334,122.000000,296.000000,3,0,3,3.956522,1
0,八一路东,40,18,93833.0,1.239313,1246.400000,0.450000,31.160000,106.707143,5.800000,219.000000,0,0,0,4.700000,1
0,凯丹广场,18,17,18916.0,2.287362,1521.099998,0.944444,84.505555,113.714583,46.333333,167.500000,1,1,0,4.888889,1
0,黑石礁,53,13,62787.0,0.917892,1089.000000,0.245283,20.547170,57.361111,15.000000,121.166667,3,1,1,4.792453,1
0,大连科技学院,24,11,32159.0,0.779028,1239.000000,0.458333,51.625000,101.333333,30.000000,173.000000,1,1,0,4.500000,1
0,百合,12,11,56264.0,1.378954,1992.800026,0.916667,166.066669,182.186669,158.880002,193.439999,1,0,0,5.166667,1
0,大连理工大学,9,3,9275.0,0.707107,299.500000,0.333333,33.277778,105.000000,89.500000,120.500000,1,0,1,4.888889,1
0,大连交通大学（旅顺校区）,8,2,8456.0,0.707107,158.000000,0.250000,19.750000,79.000000,79.000000,79.000000,0,0,0,4.500000,1
0,辽宁对外经贸学院,16,1,76714.0,0.250000,118.000000,0.062500,7.375000,118.000000,118.000000,118.000000,0,0,0,4.500000,1
0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0.000000,0
0,大连大学,2,0,652.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,7.500000,1

In [31]:
data_fengwo['订单数'].sum()
data_fengwo['订单数'].count()

60

In [38]:
enght = df[df['时间'] == 8 ]
enght_fengwo= roin(enght,'蜂窝')
enght_fengwo['门店总数'].sum()

<ipython-input-19-df31c56da28f>:20: RuntimeWarning: invalid value encountered in longlong_scalars
  dingdan_mean = dingdan_sum/df_for_x['门店ID'].count()
<ipython-input-19-df31c56da28f>:22: RuntimeWarning: invalid value encountered in double_scalars
  jin_mean = jin_sum/df_for_x['门店ID'].count()

586

In [39]:
enght = data[data['时间'] == 8 ]
enght_fengwo= roin(enght,'蜂窝')
enght_fengwo['门店总数'].sum()

<ipython-input-19-df31c56da28f>:20: RuntimeWarning: invalid value encountered in longlong_scalars
  dingdan_mean = dingdan_sum/df_for_x['门店ID'].count()
<ipython-input-19-df31c56da28f>:22: RuntimeWarning: invalid value encountered in double_scalars
  jin_mean = jin_sum/df_for_x['门店ID'].count()

443

In [ ]:
enght = data[data['时间'] == 8 ]
enght_fengwo= roin(enght,'蜂窝')
enght_fengwo['门店总数'].sum()

In [42]:
data_fengwo

,蜂窝,门店总数,订单数,曝光人数,订单方差,实付交易额,平均订单数,平均金额,均客单价,最小客单价,最大客单价,非议订单数,拒单,不接订单,time,蜂窝数量
0,软件园,32,6824,318436.0,401.580667,703303.080289,213.250000,21978.221259,96.146195,24.000000,142.000000,90,3,1,4.500000,1
0,辽宁师范大学海华学院,34,4070,345009.0,231.670943,275010.299884,119.705882,8088.538232,81.417370,20.956522,129.844828,24,2,1,4.705882,1
0,锦辉广场,70,3120,307670.0,139.563873,181956.590018,44.571429,2599.379857,96.741807,16.000000,225.880005,69,3,1,5.171429,1
0,大连交通大学,43,2250,275120.0,112.761383,223476.609816,52.325581,5197.130461,100.635843,28.768421,193.000000,53,12,4,4.674419,1
0,万和汇,111,1924,546783.0,38.127855,213022.830085,17.333333,1919.124595,103.452042,4.500000,289.000000,117,10,1,4.972973,1
0,凯旋,68,1676,313649.0,50.711288,216387.989994,24.647059,3182.176323,120.964947,1.000000,234.125000,64,18,2,4.485294,1
0,东方圣克拉,81,1256,375296.0,32.464644,136012.890091,15.506173,1679.171483,126.860963,69.484153,266.572964,59,6,0,5.160494,1
0,金三角,50,1249,436266.0,48.964164,171929.430119,24.980000,3438.588602,140.100326,44.100000,349.227273,89,6,3,5.260000,1
0,沙河口,103,1106,287280.0,24.392606,95310.780063,10.737864,925.347379,99.894181,2.677143,287.187500,57,6,3,5.000000,1
0,万达广场,115,1075,578045.0,13.190935,108892.640037,9.347826,946.892522,113.864254,18.860000,338.000000,34,6,5,4.660870,1
0,奥林匹克,144,910,573142.0,18.953256,116208.860048,6.319444,807.005973,155.286822,17.500000,412.000000,44,14,4,4.652778,1
0,金州古城,115,810,389152.0,14.717451,87696.550013,7.043478,762.578696,111.448397,3.981818,237.000000,47,2,1,4.600000,1
0,时代广场,22,750,61876.0,99.168404,85377.499992,34.090909,3880.795454,98.834163,39.842105,127.000000,84,3,0,5.681818,1
0,罗斯福,15,676,94422.0,103.778932,23947.499997,45.066667,1596.500000,78.234549,13.981333,255.000000,2,0,0,2.600000,1
0,南山,77,653,249839.0,14.443730,92688.649959,8.480519,1203.748701,120.287342,2.100000,224.000000,41,10,10,4.753247,1
0,中长街,41,575,109484.0,36.041981,24000.759955,14.024390,585.384389,85.129919,21.989423,250.000000,8,1,0,4.658537,1
0,金州安盛,77,523,235087.0,23.951342,61493.920019,6.792208,798.622338,118.220995,11.250000,217.000000,36,10,1,4.649351,1
0,金州体育场,63,473,225835.0,16.000880,68165.379806,7.507937,1081.990156,123.732805,17.176190,246.961626,29,3,0,4.587302,1
0,东北财经大学,13,440,67605.0,19.234718,46188.130005,33.846154,3552.933077,110.732416,78.497465,153.855554,26,3,6,5.076923,1
0,旅顺新开,58,423,311848.0,20.036816,57367.519977,7.293103,989.095172,150.591060,5.000000,480.000000,13,2,2,5.155172,1
0,春柳东,74,415,278674.0,20.091447,31774.099913,5.608108,429.379729,124.131730,21.698101,208.000000,23,7,1,4.648649,1
0,张前路乐购,35,320,161419.0,26.451001,40072.540009,9.142857,1144.929715,187.057972,2.000000,862.500000,23,1,0,5.114286,1
0,高新万达,61,314,172953.0,11.367844,24501.999931,5.147541,401.672130,115.109851,18.537500,881.200012,26,8,3,4.770492,1
0,青泥洼,49,271,80466.0,17.012375,17245.380066,5.530612,351.946532,93.536513,42.296809,188.500000,12,4,2,5.265306,1
0,五一广场,46,265,165428.0,10.411926,34423.219995,5.760870,748.330869,124.121067,70.625000,242.090909,15,1,2,4.739130,1
0,红梅,62,236,144915.0,8.875900,28538.260086,3.806452,460.294518,141.994963,72.000000,436.000000,11,4,0,4.629032,1
0,太原街,25,230,96803.0,25.818275,6607.099921,9.200000,264.283997,166.897194,17.076744,595.000000,2,0,0,4.360000,1
0,亿合城,25,223,97396.0,15.269578,27627.449989,8.920000,1105.098000,124.872407,26.496875,266.500000,9,1,0,6.680000,1
0,南关岭,39,215,237682.0,7.660122,28542.090057,5.512821,731.848463,126.444241,62.000000,252.690001,12,1,2,5.641026,1
0,友好广场,28,210,100028.0,17.336538,25056.759968,7.500000,894.884285,170.338841,25.000000,804.500000,26,3,0,4.214286,1
0,辽宁师范大学,52,208,81843.0,15.770412,7545.100001,4.000000,145.098077,80.667392,9.000000,222.333333,1,1,0,5.057692,1
0,华南广场,40,192,161373.0,13.582039,24411.520000,4.800000,610.288000,145.387180,22.799999,313.500000,16,1,3,4.875000,1
0,千山路,73,179,150126.0,9.823499,30237.000000,2.452055,414.205479,161.922815,65.000000,358.000000,16,4,3,4.698630,1
0,和平广场,63,171,226696.0,6.230592,18020.160004,2.714286,286.034286,133.009802,17.199999,391.839996,14,5,0,4.174603,1
0,二七广场,88,143,162983.0,4.191706,17207.499990,1.625000,195.539773,136.962790,22.500000,389.000000,8,3,0,4.363636,1
0,五彩城,24,134,103911.0,9.347944,12550.400000,5.583333,522.933333,95.463045,20.000000,242.000000,5,1,3,5.041667,1
0,泉水西,69,108,153837.0,4.815655,17086.400032,1.565217,247.628986,148.672054,79.000000,220.600002,16,3,4,4.333333,1
0,锦绣,45,90,125897.0,5.547317,8911.799995,2.000000,198.040000,125.138466,52.083333,261.000000,8,2,1,5.200000,1
0,甘井子万达广场,29,81,113556.0,5.253430,6744.700001,2.793103,232.575862,102.900992,7.775000,243.166667,4,0,0,5.344828,1
0,东城天下,52,72,121782.0,2.958231,13002.020004,1.384615,250.038846,205.229239,95.333333,354.000000,2,0,1,5.019231,1
0,天津街,25,55,37258.0,6.103278,3950.400000,2.200000,158.016000,97.252421,40.882353,183.000000,1,1,0,4.640000,1
0,春柳西,77,51,49483.0,3.526629,5602.359994,0.662338,72.757922,109.472667,0.230000,188.000000,5,4,1,4.805195,1
0,旅顺新玛特,64,43,127663.0,1.285508,3800.319996,0.671875,59.380000,107.086458,10.666667,319.049988,1,0,0,4.625000,1
0,泡崖子,30,41,72899.0,2.894505,4908.300020,1.366667,163.610001,107.109694,49.900002,231.050001,6,2,1,4.733333,1
0,八一路西,34,39,55071.0,2.524214,2808.700008,1.147059,82.608824,93.280247,10.000000,186.000000,0,0,0,5.058824,1
0,红星海,30,37,30975.0,3.147887,3951.599997,1.233333,131.720000,181.927936,30.000000,535.000000,0,0,0,4.833333,1
0,大连民族大学,16,34,26985.0,2.680174,4839.760014,2.125000,302.485001,174.713228,114.590002,469.989990,2,1,0,3.750000,1
0,小平岛,49,34,61410.0,2.043323,2376.900000,0.693878,48.508163,87.119365,10.900000,167.500000,4,2,1,4.918367,1
0,马栏广场,42,30,127125.0,1.469789,2194.800008,0.714286,52.257143,93.041026,7.150000,219.900002,2,0,1,4.976190,1
0,泉水东,23,19,109524.0,1.922408,3051.860016,0.826087,132.689566,182.463334,122.000000,296.000000,3,0,3,3.956522,1
0,八一路东,40,18,93833.0,1.239313,1246.400000,0.450000,31.160000,106.707143,5.800000,219.000000,0,0,0,4.700000,1
0,凯丹广场,18,17,18916.0,2.287362,1521.099998,0.944444,84.505555,113.714583,46.333333,167.500000,1,1,0,4.888889,1
0,黑石礁,53,13,62787.0,0.917892,1089.000000,0.245283,20.547170,57.361111,15.000000,121.166667,3,1,1,4.792453,1
0,大连科技学院,24,11,32159.0,0.779028,1239.000000,0.458333,51.625000,101.333333,30.000000,173.000000,1,1,0,4.500000,1
0,百合,12,11,56264.0,1.378954,1992.800026,0.916667,166.066669,182.186669,158.880002,193.439999,1,0,0,5.166667,1
0,大连理工大学,9,3,9275.0,0.707107,299.500000,0.333333,33.277778,105.000000,89.500000,120.500000,1,0,1,4.888889,1
0,大连交通大学（旅顺校区）,8,2,8456.0,0.707107,158.000000,0.250000,19.750000,79.000000,79.000000,79.000000,0,0,0,4.500000,1
0,辽宁对外经贸学院,16,1,76714.0,0.250000,118.000000,0.062500,7.375000,118.000000,118.000000,118.000000,0,0,0,4.500000,1
0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0.000000,0
0,大连大学,2,0,652.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,7.500000,1

In [59]:
def roin_(data,object_):
    pinpai_ID = data.drop_duplicates(subset=object_,inplace=False)
    pinpai_list_ID = list(pinpai_ID[object_])
    pinpai_dict_list = []
    
    
    for nameid in pinpai_list_ID:
        for_dict = {}
        
        
        df_for_x = data[data[object_] == nameid ]
        
        mendian_name = list(df_for_x['门店名称'])[0]
        fengwo_name = list(df_for_x['蜂窝'])[0]
#         品牌ID
        pinpaiid =  list(df_for_x['品牌ID'])[0]
    #     订单方差
        dingdan_std =  df_for_x['订单数'].std()
    #     订单总数
        dingdan_sum =  df_for_x['订单数'].sum()
#         曝光人数
        dingdan_baoguangrenshu  =  df_for_x['曝光人数'].sum()
    #     金额总数
        jin_sum =  df_for_x['实付交易额'].sum()
    #     均客单价
        kedanjia_mean = df_for_x['客单价'].mean()
    #     最小客单价
        kedanjia_min = df_for_x['客单价'].min()
    #     最大客单价
        kedanjia_max = df_for_x['客单价'].max()
    #     非议订单
        feiyi =  df_for_x['非异订单数'].sum()
    #     拒单
        judan  =  df_for_x['商家拒单订单数'].sum()
    #     bujied不接单
        bujiedan =  df_for_x['商家不接单订单数'].sum()
    #     投诉D单
        tousu =  df_for_x['商家违规投诉订单数'].sum()
        
        time =  df_for_x['时间'].mean()

        pinpai_dict_list__count = df_for_x.drop_duplicates(subset = '蜂窝')['蜂窝'].count()
        for_dict['门店名称'] = mendian_name
        for_dict['品牌ID'] = pinpaiid
        for_dict['均客单价'] = kedanjia_mean
        for_dict[object_] = nameid
        for_dict['门店开业时间'] = df_for_x['门店ID'].count()
        for_dict['订单数'] = dingdan_sum
        for_dict['曝光人数'] = dingdan_baoguangrenshu
        for_dict['订单方差'] = dingdan_std
        for_dict['实付交易额'] = jin_sum
        for_dict['蜂窝'] = fengwo_name
        for_dict['最小客单价'] = kedanjia_min
        for_dict['最大客单价'] = kedanjia_max
        for_dict['非议订单数'] = feiyi
        for_dict['拒单'] = judan
        for_dict['不接订单'] = bujiedan
        for_dict['time'] = time
        pinpai_dict_list.append(for_dict) 
    for i in range(len(pinpai_dict_list)):

        dataframe_i = pd.DataFrame([pinpai_dict_list[i]])
        dataframe_i = dataframe_i.fillna(0)
        if i == 0:
            pinpai_dict_dataframe1 = dataframe_i
        else:
            pinpai_dict_dataframe1 = pd.concat([pinpai_dict_dataframe1,dataframe_i],axis=0)
    
    pinpai_dict_dataframe1 = pinpai_dict_dataframe1.sort_values(by='订单数',ascending=False)
    
    return pinpai_dict_dataframe1

In [66]:
sandian_data = roin_(data,'门店ID')

In [67]:
short_time_mendian = sandian_data[sandian_data['门店开业时间'] < 3]

In [68]:
short_time_mendian.sort_values(by='订单数',ascending = False)

,门店名称,品牌ID,均客单价,门店ID,门店开业时间,订单数,曝光人数,订单方差,实付交易额,蜂窝,最小客单价,最大客单价,非议订单数,拒单,不接订单,time
0,伊朵鲜花,0,21.698101,9633914,2,158,12009.0,111.722871,3428.299945,春柳东,21.698101,21.698101,0,0,0,7.5
0,心语鲜花坊,0,82.892979,9477096,2,55,8459.0,27.577164,4730.440033,青泥洼,78.500001,87.285958,1,0,0,7.5
0,简爱鲜花店,0,52.168605,9602926,2,49,11039.0,26.162951,2026.000000,辽宁师范大学,37.837209,66.500000,0,0,0,7.5
0,遇爱鲜花店,0,43.945946,8740086,1,37,6653.0,0.000000,1626.000000,沙河口,43.945946,43.945946,0,0,0,8.0
0,W FLOWER STUDIO鲜花店,0,17.269231,9644786,1,26,9094.0,0.000000,449.000000,沙河口,17.269231,17.269231,0,0,0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,花田喜铺,0,0.000000,9799598,1,0,227.0,0.000000,0.000000,五彩城,0.000000,0.000000,0,0,0,8.0
0,J.Florist今花店,0,0.000000,9715658,1,0,749.0,0.000000,0.000000,锦辉广场,0.000000,0.000000,0,0,0,8.0
0,诗梦鲜花店,0,0.000000,9777846,1,0,54.0,0.000000,0.000000,时代广场,0.000000,0.000000,0,0,0,8.0
0,温馨鲜花,0,0.000000,9805107,1,0,318.0,0.000000,0.000000,0,0.000000,0.000000,0,0,0,8.0
0,路上有花鲜花店,0,0.000000,9822091,1,0,2003.0,0.000000,0.000000,青泥洼,0.000000,0.000000,0,0,0,8.0

In [72]:
sandian_data_300 = sandian_data[sandian_data['订单数'] > 300]
sandian_data_300.to_csv('大于300单门店.csv')

In [75]:
sandian_data

,门店名称,品牌ID,均客单价,门店ID,门店开业时间,订单数,曝光人数,订单方差,实付交易额,蜂窝,最小客单价,最大客单价,非议订单数,拒单,不接订单,time
0,初见鲜花店,0,105.751019,6025260,8,6810,260724.0,306.452863,701915.080289,软件园,89.045322,119.998918,90,3,1,4.5
0,弎生鲜花店,0,81.149460,7350344,8,3864,237970.0,234.278833,253711.599883,辽宁师范大学海华学院,34.875174,118.719000,16,2,1,4.5
0,万卉源花艺坊,0,63.923668,8109454,8,2992,160772.0,227.485635,168555.269978,锦辉广场,41.329013,90.870000,65,3,0,4.5
0,香恋鲜花店,0,111.255073,6655102,8,2078,196532.0,124.249461,208923.299816,大连交通大学,60.698242,148.191304,38,8,2,4.5
0,真情花屋,0,114.685394,7277181,8,954,128689.0,72.343921,108958.770050,万和汇,92.949530,140.132278,68,2,0,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,艺贯花铺,0,0.000000,8812042,2,0,2814.0,0.000000,0.000000,0,0.000000,0.000000,0,0,0,4.5
0,花语鲜花,0,0.000000,5532332,8,0,2404.0,0.000000,0.000000,春柳西,0.000000,0.000000,0,0,0,4.5
0,花语轩花艺,0,0.000000,5471737,8,0,7007.0,0.000000,0.000000,泡崖子,0.000000,0.000000,0,0,0,4.5
0,卉萃源鲜花水吧,0,0.000000,5444450,8,0,17778.0,0.000000,0.000000,辽宁师范大学,0.000000,0.000000,0,0,0,4.5
0,路上有花鲜花店,0,0.000000,9822091,1,0,2003.0,0.000000,0.000000,青泥洼,0.000000,0.000000,0,0,0,8.0

In [78]:
data_fengwo[data_fengwo['门店总数'] < 40]

,蜂窝,门店总数,订单数,曝光人数,订单方差,实付交易额,平均订单数,平均金额,均客单价,最小客单价,最大客单价,非议订单数,拒单,不接订单,time,蜂窝数量
0,软件园,32,6824,318436.0,401.580667,703303.080289,213.250000,21978.221259,96.146195,24.000000,142.000000,90,3,1,4.500000,1
0,辽宁师范大学海华学院,34,4070,345009.0,231.670943,275010.299884,119.705882,8088.538232,81.417370,20.956522,129.844828,24,2,1,4.705882,1
0,时代广场,22,750,61876.0,99.168404,85377.499992,34.090909,3880.795454,98.834163,39.842105,127.000000,84,3,0,5.681818,1
0,罗斯福,15,676,94422.0,103.778932,23947.499997,45.066667,1596.500000,78.234549,13.981333,255.000000,2,0,0,2.600000,1
0,东北财经大学,13,440,67605.0,19.234718,46188.130005,33.846154,3552.933077,110.732416,78.497465,153.855554,26,3,6,5.076923,1
0,张前路乐购,35,320,161419.0,26.451001,40072.540009,9.142857,1144.929715,187.057972,2.000000,862.500000,23,1,0,5.114286,1
0,太原街,25,230,96803.0,25.818275,6607.099921,9.200000,264.283997,166.897194,17.076744,595.000000,2,0,0,4.360000,1
0,亿合城,25,223,97396.0,15.269578,27627.449989,8.920000,1105.098000,124.872407,26.496875,266.500000,9,1,0,6.680000,1
0,南关岭,39,215,237682.0,7.660122,28542.090057,5.512821,731.848463,126.444241,62.000000,252.690001,12,1,2,5.641026,1
0,友好广场,28,210,100028.0,17.336538,25056.759968,7.500000,894.884285,170.338841,25.000000,804.500000,26,3,0,4.214286,1
0,五彩城,24,134,103911.0,9.347944,12550.400000,5.583333,522.933333,95.463045,20.000000,242.000000,5,1,3,5.041667,1
0,甘井子万达广场,29,81,113556.0,5.253430,6744.700001,2.793103,232.575862,102.900992,7.775000,243.166667,4,0,0,5.344828,1
0,天津街,25,55,37258.0,6.103278,3950.400000,2.200000,158.016000,97.252421,40.882353,183.000000,1,1,0,4.640000,1
0,泡崖子,30,41,72899.0,2.894505,4908.300020,1.366667,163.610001,107.109694,49.900002,231.050001,6,2,1,4.733333,1
0,八一路西,34,39,55071.0,2.524214,2808.700008,1.147059,82.608824,93.280247,10.000000,186.000000,0,0,0,5.058824,1
0,红星海,30,37,30975.0,3.147887,3951.599997,1.233333,131.720000,181.927936,30.000000,535.000000,0,0,0,4.833333,1
0,大连民族大学,16,34,26985.0,2.680174,4839.760014,2.125000,302.485001,174.713228,114.590002,469.989990,2,1,0,3.750000,1
0,泉水东,23,19,109524.0,1.922408,3051.860016,0.826087,132.689566,182.463334,122.000000,296.000000,3,0,3,3.956522,1
0,凯丹广场,18,17,18916.0,2.287362,1521.099998,0.944444,84.505555,113.714583,46.333333,167.500000,1,1,0,4.888889,1
0,大连科技学院,24,11,32159.0,0.779028,1239.000000,0.458333,51.625000,101.333333,30.000000,173.000000,1,1,0,4.500000,1
0,百合,12,11,56264.0,1.378954,1992.800026,0.916667,166.066669,182.186669,158.880002,193.439999,1,0,0,5.166667,1
0,大连理工大学,9,3,9275.0,0.707107,299.500000,0.333333,33.277778,105.000000,89.500000,120.500000,1,0,1,4.888889,1
0,大连交通大学（旅顺校区）,8,2,8456.0,0.707107,158.000000,0.250000,19.750000,79.000000,79.000000,79.000000,0,0,0,4.500000,1
0,辽宁对外经贸学院,16,1,76714.0,0.250000,118.000000,0.062500,7.375000,118.000000,118.000000,118.000000,0,0,0,4.500000,1
0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0.000000,0
0,大连大学,2,0,652.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,7.500000,1

In [79]:
x_list = ['软件园','辽宁师范大学海华学院','时代广场','罗斯福','东北财经大学']

In [81]:
for i in x_list:
    a = sandian_data[sandian_data['蜂窝'] == i]
    a.to_csv(i + '.csv')